import type { Preset } from 'unocss'

export function presetThevetatColors(): Preset {
  return {
    name: 'unocss-preset-thevetat-colors',

    shortcuts: [
      ['color-trans', 'transition-colors duration-200 ease-in-out'],
      ['border-color', 'border border-gray-g-200'],
      ['primary-button-shadow', 'shadow-[0px_10.644px_30.64px_0px_rgba(53,35,104,0.18)]'],
    ],

    theme: {
      colors: {
        'primary-light': '#886aaf',
        'primary-light-hover': '#997fba',
        'primary-lighter': '#c4b2ec',
        'primary-lightest': '#e0d3ed',
        'primary-light-bg': '#f6f4f9',
        'primary': '#352368',
        'primary-p-100': '#F5F4F7',
        'purple': '#2a0d61',
        'p-500': '#5d4f86',
        'bp-300': '#6A5B88',
        'bp-400': '#493F5E',
        'main-bright-purple': '#836DDD',
        'light-purple-50': '#F6F4F9',
        'light-purple-300': '#C3B4D7',
        'accents': '#1579d6',
        'accents-s-400': '#5ea9ef',
        'color-black': '#000000',
        'main-black': '#070608',
        'light-white': '#f8f9fa',
        'link-color': '#352368',
        'link-light': '#bcb4df',
        'link-lightest': '#aea7c3',
        'link-color-nav': '#ffffff',
        'mixed-white': '#dae1e7',
        'color-white-light': '#f7f7f7',
        'color-white': '#ffffff',
        'color-orange': '#e77600',
        'orange-light': '#f9a661',
        'orange-text': '#ff8300',
        'orange-error-text': '#f15524',
        'orange-S-100': '#ffebd8',
        'orange-S-200': '#ffd6b0',
        'orange-S-300': '#ffb875',
        'fad-White': '#ebebeb',
        'gray-middle-level': '#555555',
        'gray-g-300': '#F5F5F6',
        'gray-top-level': '#47494a',
        'gray-text-input': '#4b566b',
        'gray-low-level': '#b4aca8',
        'gray-soft-border': '#fafafa',
        'card-shadow': '#eeeeee',
        'gray-seperator': '#e5e5e5',
        'text-gray': '#808080',
        'grey-claim': '#666666',
        'pg-grey': '#656469',
        'credit-grey': '#4d4d4d',
        'step-color': '#cbcbcb',
        'layout-color': '#e6e6e6',
        'faded-purple': '#e7dcf1',
        'color-catg': '#333333',
        'sky-blue': '#e3e9ef',
        'grey-bar': '#777777',
        'dark-cyan': '#212529',
        'grey-cc': '#cccccc',
        'color-gray': '#f3f3f3',
        'grey-color': '#b3b3b3',
        'grey-lighter-color': '#f6f6f6',
        'gray-200': '#e9ecef',
        'gray-100': '#e5e5e5',
        'gray-g-200': '#e1e0e4',
        'gray-7867': '#787676',
        'bg-gray': '#e0d3ed80',
        'gray-lightest': '#eed0d0c6',
        'gray-light': '#dfdfdf',
        'gray-dad-color': '#dadce0',
        'gray-ceca-color': '#cecaca',
        'gray-f8f9-color': '#f8f9fa',
        'gray-divider': '#f2f2f2',
        'gray-table-th': '#726f81',
        'gray-table-td': '#070608',
        'gray-fafb': '#fafafb',
        'main-gray': '#726f81',
        'gray-300': '#cccbd2',
        'gray-400': '#a4a2ae',
        'gray-border-light': '#aaaaaa',
        'gray-border-lighter': '#e5dfee',
        'gray-filter-text': '#908d9c',
        'gray-lightes-bg': 'F1F1F1',
        'color-red': '#ff0000',
        'color-danger': '#d20000',
        'danger-light': '#f56c6c',
        'primary-blue': '#146cda',
        'hippa-link': '#5d5fef',
        'darker-purple': '#271c46',
        'secondary-blue': '#7a3bff',
        'light-blue': '#f2f8fb',
        'color-green': '#3a8700',
        'color-green-light': '#82b24f',
        'status-completed': '#ecf8ed',
      },
    },
    safelist: [
      'primary-button-shadow',
    ],
  }
}

export default presetThevetatColors
