export const finished = [
  {
    uuid: null,
    screenings: [
      {
        templateId: 'CSHRST2025',
        screeningId: 'a0EO3000006vG6WMAU',
        relatedCases: [
          {
            caseNumber: '00042817',
          },
        ],
        questions: [
          {
            yesIsPositive: false,
            status: false,
            questionText: 'Please provide your phone number',
            questionId: 'a0DO300000BD1HiMAL',
            questionClassification: 'Demographic',
            payer: 'Clear Spring',
            loincCode: null,
            isRequired: false,
            isPositive: false,
            isAnswerValuePopulated: false,
            hasTextDetail: true,
            externalquestionId: 'CS25Q01',
            expirationDate: '2025-12-31',
            ehrKey: null,
            dateFormat: null,
            children: null,
            childDependentValue: null,
            answerType: 'Text',
            answerPicklistChoices: [],
            answerDetails: null,
            answer: null,
            activityDomain: null,
            activationDate: '2025-01-01',
          },
          {
            yesIsPositive: false,
            status: false,
            questionText: 'Date of Birth:',
            questionId: 'a0DO300000BD1HkMAL',
            questionClassification: 'Demographic',
            payer: 'Clear Spring',
            loincCode: null,
            isRequired: false,
            isPositive: false,
            isAnswerValuePopulated: false,
            hasTextDetail: false,
            externalquestionId: 'CS25Q04',
            expirationDate: '2025-12-31',
            ehrKey: null,
            dateFormat: 'MM-DD-YYYY',
            children: null,
            childDependentValue: null,
            answerType: 'Date',
            answerPicklistChoices: [],
            answerDetails: null,
            answer: null,
            activityDomain: null,
            activationDate: '2025-01-01',
          },
          {
            yesIsPositive: false,
            status: false,
            questionText: 'What is your main health concern right now?',
            questionId: 'a0DO300000BD1ILMA1',
            questionClassification: 'Medical',
            payer: 'Clear Spring',
            loincCode: null,
            isRequired: false,
            isPositive: false,
            isAnswerValuePopulated: false,
            hasTextDetail: true,
            externalquestionId: 'CS25Q65',
            expirationDate: '2025-12-31',
            ehrKey: null,
            dateFormat: null,
            children: null,
            childDependentValue: null,
            answerType: 'Text',
            answerPicklistChoices: [],
            answerDetails: null,
            answer: null,
            activityDomain: null,
            activationDate: '2025-01-01',
          },
        ],
        name: 'Clear Spring-2025-HRA',
        isStarted: false,
        isCompleted: false,
        completionDate: null,
        agentName: 'Porter Scheduling Team',
      },
    ],
    message: null,
    memberName: 'Westfield G Montgomery',
    memberLifetimeID: null,
    memberId: null,
    memberDOB: '7/2/1962',
    mbi: null,
    hContract: null,
  },
]
