export const finished = [
  {
    uuid: null,
    screenings: [
      {
        templateId: 'CSHRST2025',
        screeningId: 'a0EO3000006vG6WMAU',
        relatedCases: [
          {
            caseNumber: '00042817',
          },
        ],
        questions: [
          {
            yesIsPositive: false,
            status: false,
            questionText: 'Have you had any of the following preventative screenings?',
            questionId: 'a0DO300000BD1IGMA1',
            questionClassification: 'Medical',
            payer: 'Clear Spring',
            loincCode: null,
            isRequired: false,
            isPositive: false,
            isAnswerValuePopulated: false,
            hasTextDetail: false,
            externalquestionId: 'CS25Q59',
            expirationDate: '2025-12-31',
            ehrKey: null,
            dateFormat: null,
            children: [
              {
                yesIsPositive: false,
                status: false,
                questionText: 'Colorectal Cancer Screening (for all ages 45 and above)',
                questionId: 'a0DO300000BD1J0MAL',
                questionClassification: 'Medical',
                payer: 'Clear Spring',
                loincCode: null,
                isRequired: true,
                isPositive: false,
                isAnswerValuePopulated: false,
                hasTextDetail: false,
                externalquestionId: 'CS25Q595',
                expirationDate: '2025-12-31',
                ehrKey: null,
                dateFormat: null,
                children: [
                  {
                    yesIsPositive: false,
                    status: false,
                    questionText: 'Please select the types of Colorectal Cancer Screening you\'ve had',
                    questionId: 'a0DO300000BD1J9MAL',
                    questionClassification: 'Medical',
                    payer: 'Clear Spring',
                    loincCode: null,
                    isRequired: false,
                    isPositive: false,
                    isAnswerValuePopulated: false,
                    hasTextDetail: false,
                    externalquestionId: 'CS25Q596',
                    expirationDate: '2025-12-31',
                    ehrKey: null,
                    dateFormat: null,
                    children: null,
                    childDependentValue: 'Yes',
                    answerType: 'Select Multiple',
                    answerPicklistChoices: [
                      'FOBT (Occult Blood in the Stool)',
                      'Flexible Sigmoidoscopy',
                      'Colonoscopy',
                      'Cologuard',
                      'CT-Colonography',
                      'None',
                    ],
                    answerDetails: null,
                    answer: null,
                    activityDomain: 'Access to Care',
                    activationDate: '2025-01-01',
                  },
                  {
                    yesIsPositive: false,
                    status: false,
                    questionText: 'Date of last Colorectal Cancer Screening: (type N/A if none)',
                    questionId: 'a0DO300000BD1JAMA1',
                    questionClassification: 'Medical',
                    payer: 'Clear Spring',
                    loincCode: null,
                    isRequired: true,
                    isPositive: false,
                    isAnswerValuePopulated: false,
                    hasTextDetail: true,
                    externalquestionId: 'CS25Q597',
                    expirationDate: '2025-12-31',
                    ehrKey: null,
                    dateFormat: null,
                    children: null,
                    childDependentValue: 'Yes',
                    answerType: 'Text',
                    answerPicklistChoices: [],
                    answerDetails: null,
                    answer: null,
                    activityDomain: 'Access to Care',
                    activationDate: '2025-01-01',
                  },
                  {
                    yesIsPositive: false,
                    status: false,
                    questionText: 'Results of last Colorectal Cancer Screening',
                    questionId: 'a0DO300000BD1JBMA1',
                    questionClassification: 'Medical',
                    payer: 'Clear Spring',
                    loincCode: null,
                    isRequired: false,
                    isPositive: false,
                    isAnswerValuePopulated: false,
                    hasTextDetail: false,
                    externalquestionId: 'CS25Q598',
                    expirationDate: '2025-12-31',
                    ehrKey: null,
                    dateFormat: null,
                    children: null,
                    childDependentValue: 'Yes',
                    answerType: 'Select Single',
                    answerPicklistChoices: [
                      'Normal',
                      'Abnormal',
                      'N/A (only select if no Screenings performed)',
                    ],
                    answerDetails: null,
                    answer: null,
                    activityDomain: 'Access to Care',
                    activationDate: '2025-01-01',
                  },
                ],
                childDependentValue: null,
                answerType: 'Select Single',
                answerPicklistChoices: [
                  'Yes',
                  'No',
                  'N/A',
                ],
                answerDetails: null,
                answer: null,
                activityDomain: 'Access to Care',
                activationDate: '2025-01-01',
              },
            ],
            childDependentValue: null,
            answerType: null,
            answerPicklistChoices: [],
            answerDetails: null,
            answer: null,
            activityDomain: null,
            activationDate: '2025-01-01',
          },
          {
            yesIsPositive: false,
            status: false,
            questionText: 'Have you had a Flu Vaccine in the last year?',
            questionId: 'a0DO300000BD1IUMA1',
            questionClassification: 'Medical',
            payer: 'Clear Spring',
            loincCode: null,
            isRequired: true,
            isPositive: false,
            isAnswerValuePopulated: false,
            hasTextDetail: false,
            externalquestionId: 'CS25Q60',
            expirationDate: '2025-12-31',
            ehrKey: null,
            dateFormat: null,
            children: null,
            childDependentValue: null,
            answerType: 'Select Single',
            answerPicklistChoices: [
              'Yes',
              'No',
            ],
            answerDetails: null,
            answer: null,
            activityDomain: null,
            activationDate: '2024-01-01',
          },
          {
            yesIsPositive: false,
            status: false,
            questionText: 'What is your main health concern right now?',
            questionId: 'a0DO300000BD1ILMA1',
            questionClassification: 'Medical',
            payer: 'Clear Spring',
            loincCode: null,
            isRequired: false,
            isPositive: false,
            isAnswerValuePopulated: false,
            hasTextDetail: true,
            externalquestionId: 'CS25Q65',
            expirationDate: '2025-12-31',
            ehrKey: null,
            dateFormat: null,
            children: null,
            childDependentValue: null,
            answerType: 'Text',
            answerPicklistChoices: [],
            answerDetails: null,
            answer: null,
            activityDomain: null,
            activationDate: '2025-01-01',
          },
        ],
        name: 'Clear Spring-2025-HRA',
        isStarted: false,
        isCompleted: false,
        completionDate: null,
        agentName: 'Porter Scheduling Team',
      },
    ],
    message: null,
    memberName: 'Westfield G Montgomery',
    memberLifetimeID: null,
    memberId: null,
    memberDOB: '7/2/1962',
    mbi: null,
    hContract: null,
  },
]
