export const finishedHealthyman = {
  screening: {
    templateId: null,
    screeningId: 'a0EO3000004otQPMAY',
    relatedCases: [
      {
        caseNumber: '00042599',
      },
    ],
    questions: [
      {
        questionText: 'What is your preferred language for health communications?',
        questionId: 'a0DO3000009Fk5OMAS',
        children: [
          {
            questionText: 'Please specify if Other:',
            questionId: 'a0DO3000009Fk5fMAC',
            children: null,
            childDependentValue: 'Other (Please Specify)',
            answerType: 'Text',
            dateFormat: null,
            answerDetails: null,
            answerPicklistChoices: [],
            answer: null,
            activationDate: null,
            activityDomain: null,
            expirationDate: null,
            loincCode: null,
            questionClassification: null,
            status: false,
            isPositive: false,
            yesIsPositive: false,
            payer: null,
            isAnswerValuePopulated: false,
            externalquestionId: null,
            ehrKey: null,
            hasTextDetail: true,
          },
        ],
        childDependentValue: null,
        answerType: 'Select Single',
        dateFormat: null,
        answerDetails: null,
        answerPicklistChoices: [
          'English',
          'Spanish',
          'Other (Please Specify)',
        ],
        answer: null,
        activationDate: null,
        activityDomain: null,
        expirationDate: null,
        loincCode: null,
        questionClassification: null,
        status: false,
        isPositive: false,
        yesIsPositive: false,
        payer: null,
        isAnswerValuePopulated: false,
        externalquestionId: null,
        ehrKey: null,
        hasTextDetail: false,
      },
      {
        questionText: 'How would you rate your overall health?',
        questionId: 'a0DO3000009Fk5NMAS',
        children: null,
        childDependentValue: null,
        answerType: 'Select Single',
        dateFormat: null,
        answerDetails: null,
        answerPicklistChoices: [
          'Excellent',
          'Good',
          'Fair',
          'Poor',
        ],
        answer: null,
        activationDate: null,
        activityDomain: null,
        expirationDate: null,
        loincCode: null,
        questionClassification: null,
        status: false,
        isPositive: false,
        yesIsPositive: false,
        payer: null,
        isAnswerValuePopulated: false,
        externalquestionId: null,
        ehrKey: null,
        hasTextDetail: false,
      },
      {
        questionText: 'Do you have a Primary Care Physician (PCP) that you see?',
        questionId: 'a0DO3000009Fk5QMAS',
        children: null,
        childDependentValue: null,
        answerType: 'Select Single',
        dateFormat: null,
        answerDetails: null,
        answerPicklistChoices: [
          'Yes',
          'No',
        ],
        answer: null,
        activationDate: null,
        activityDomain: null,
        expirationDate: null,
        loincCode: null,
        questionClassification: null,
        status: false,
        isPositive: false,
        yesIsPositive: false,
        payer: null,
        isAnswerValuePopulated: false,
        externalquestionId: null,
        ehrKey: null,
        hasTextDetail: false,
      },
      {
        questionText: 'Have you fallen in the last 12 months?',
        questionId: 'a0DO3000009Fk5PMAS',
        children: null,
        childDependentValue: null,
        answerType: 'Select Single',
        dateFormat: null,
        answerDetails: null,
        answerPicklistChoices: [
          'Yes',
          'No',
        ],
        answer: null,
        activationDate: null,
        activityDomain: null,
        expirationDate: null,
        loincCode: null,
        questionClassification: null,
        status: false,
        isPositive: false,
        yesIsPositive: false,
        payer: null,
        isAnswerValuePopulated: false,
        externalquestionId: null,
        ehrKey: null,
        hasTextDetail: false,
      },
      {
        questionText: 'Do you have any problems with balance or walking?',
        questionId: 'a0DO3000009Fk5RMAS',
        children: null,
        childDependentValue: null,
        answerType: 'Select Single',
        dateFormat: null,
        answerDetails: null,
        answerPicklistChoices: [
          'Yes',
          'No',
        ],
        answer: null,
        activationDate: null,
        activityDomain: null,
        expirationDate: null,
        loincCode: null,
        questionClassification: null,
        status: false,
        isPositive: false,
        yesIsPositive: false,
        payer: null,
        isAnswerValuePopulated: false,
        externalquestionId: null,
        ehrKey: null,
        hasTextDetail: false,
      },
      {
        questionText: 'Do you use any of the following to get around?  (Select all that apply)',
        questionId: 'a0DO3000009Fk5SMAS',
        children: null,
        childDependentValue: null,
        answerType: 'Select Multiple',
        dateFormat: null,
        answerDetails: null,
        answerPicklistChoices: [
          'Cane',
          'Walker',
          'Wheelchair',
          'Prosthetic Device',
          'Electric Wheelchair (scooter)',
        ],
        answer: null,
        activationDate: null,
        activityDomain: null,
        expirationDate: null,
        loincCode: null,
        questionClassification: null,
        status: false,
        isPositive: false,
        yesIsPositive: false,
        payer: null,
        isAnswerValuePopulated: false,
        externalquestionId: null,
        ehrKey: null,
        hasTextDetail: false,
      },
      {
        questionText: 'Do you have any planned surgery?',
        questionId: 'a0DO3000009Fk5ZMAS',
        children: [
          {
            questionText: 'If so, when?',
            questionId: 'a0DO3000009Fk5xMAC',
            children: null,
            childDependentValue: 'Yes',
            answerType: 'Text',
            dateFormat: null,
            answerDetails: null,
            answerPicklistChoices: [],
            answer: null,
            activationDate: null,
            activityDomain: null,
            expirationDate: null,
            loincCode: null,
            questionClassification: null,
            status: false,
            isPositive: false,
            yesIsPositive: false,
            payer: null,
            isAnswerValuePopulated: false,
            externalquestionId: null,
            ehrKey: null,
            hasTextDetail: true,
          },
        ],
        childDependentValue: null,
        answerType: 'Select Single',
        dateFormat: null,
        answerDetails: null,
        answerPicklistChoices: [
          'Yes',
          'No',
        ],
        answer: null,
        activationDate: null,
        activityDomain: null,
        expirationDate: null,
        loincCode: null,
        questionClassification: null,
        status: false,
        isPositive: false,
        yesIsPositive: false,
        payer: null,
        isAnswerValuePopulated: false,
        externalquestionId: null,
        ehrKey: null,
        hasTextDetail: false,
      },
      {
        questionText: 'Have you had any recent visits to the Emergency Department?',
        questionId: 'a0DO3000009Fk5aMAC',
        children: [
          {
            questionText: 'If so, why?',
            questionId: 'a0DO3000009Fk5yMAC',
            children: null,
            childDependentValue: 'Yes',
            answerType: 'Text',
            dateFormat: null,
            answerDetails: null,
            answerPicklistChoices: [],
            answer: null,
            activationDate: null,
            activityDomain: null,
            expirationDate: null,
            loincCode: null,
            questionClassification: null,
            status: false,
            isPositive: false,
            yesIsPositive: false,
            payer: null,
            isAnswerValuePopulated: false,
            externalquestionId: null,
            ehrKey: null,
            hasTextDetail: true,
          },
        ],
        childDependentValue: null,
        answerType: 'Select Single',
        dateFormat: null,
        answerDetails: null,
        answerPicklistChoices: [
          'Yes',
          'No',
        ],
        answer: null,
        activationDate: null,
        activityDomain: null,
        expirationDate: null,
        loincCode: null,
        questionClassification: null,
        status: false,
        isPositive: false,
        yesIsPositive: false,
        payer: null,
        isAnswerValuePopulated: false,
        externalquestionId: null,
        ehrKey: null,
        hasTextDetail: false,
      },
      {
        questionText: 'In the past 12 months, have you stayed overnight as a patient in the hospital for 2 or more nights?',
        questionId: 'a0DO3000009Fk5bMAC',
        children: [
          {
            questionText: 'If ‘Yes’, about how many times?',
            questionId: 'a0DO3000009Fk5zMAC',
            children: null,
            childDependentValue: 'Yes',
            answerType: 'Select Single',
            dateFormat: null,
            answerDetails: null,
            answerPicklistChoices: [
              '1 time',
              '2-3 times',
              '4 or more times',
            ],
            answer: null,
            activationDate: null,
            activityDomain: null,
            expirationDate: null,
            loincCode: null,
            questionClassification: null,
            status: false,
            isPositive: false,
            yesIsPositive: false,
            payer: null,
            isAnswerValuePopulated: false,
            externalquestionId: null,
            ehrKey: null,
            hasTextDetail: false,
          },
        ],
        childDependentValue: null,
        answerType: 'Select Single',
        dateFormat: null,
        answerDetails: null,
        answerPicklistChoices: [
          'Yes',
          'No',
        ],
        answer: null,
        activationDate: null,
        activityDomain: null,
        expirationDate: null,
        loincCode: null,
        questionClassification: null,
        status: false,
        isPositive: false,
        yesIsPositive: false,
        payer: null,
        isAnswerValuePopulated: false,
        externalquestionId: null,
        ehrKey: null,
        hasTextDetail: false,
      },
      {
        questionText: 'Have you ever used any type of tobacco products?',
        questionId: 'a0DO3000009Fk5cMAC',
        children: null,
        childDependentValue: null,
        answerType: 'Select Single',
        dateFormat: null,
        answerDetails: null,
        answerPicklistChoices: [
          'Current',
          'Previous',
          'Never',
        ],
        answer: null,
        activationDate: null,
        activityDomain: null,
        expirationDate: null,
        loincCode: null,
        questionClassification: null,
        status: false,
        isPositive: false,
        yesIsPositive: false,
        payer: null,
        isAnswerValuePopulated: false,
        externalquestionId: null,
        ehrKey: null,
        hasTextDetail: false,
      },
      {
        questionText: 'In the last 30 days have you (choose all that apply)',
        questionId: 'a0DO3000009Fk5dMAC',
        children: null,
        childDependentValue: null,
        answerType: 'Select Multiple',
        dateFormat: null,
        answerDetails: null,
        answerPicklistChoices: [
          'Drank more alcohol than you wanted to or has impacted your daily life',
          'Used recreational or street drugs',
          'Used prescription drugs for non-medical reasons',
          'Felt anxious, depressed, angry, lonely or socially isolated',
        ],
        answer: null,
        activationDate: null,
        activityDomain: null,
        expirationDate: null,
        loincCode: null,
        questionClassification: null,
        status: false,
        isPositive: false,
        yesIsPositive: false,
        payer: null,
        isAnswerValuePopulated: false,
        externalquestionId: null,
        ehrKey: null,
        hasTextDetail: false,
      },
      {
        questionText: 'Would you like to speak to someone about mental health or substance use services?',
        questionId: 'a0DO3000009Fk5eMAC',
        children: null,
        childDependentValue: null,
        answerType: 'Select Single',
        dateFormat: null,
        answerDetails: null,
        answerPicklistChoices: [
          'Yes',
          'No',
        ],
        answer: null,
        activationDate: null,
        activityDomain: null,
        expirationDate: null,
        loincCode: null,
        questionClassification: null,
        status: false,
        isPositive: false,
        yesIsPositive: false,
        payer: null,
        isAnswerValuePopulated: false,
        externalquestionId: null,
        ehrKey: null,
        hasTextDetail: false,
      },
      {
        questionText: 'What health conditions do you currently have?  (Please mark each condition that applies to you)',
        questionId: 'a0DO3000009Fk5VMAS',
        children: [
          {
            questionText: 'Please specify if Other:',
            questionId: 'a0DO3000009Fk5nMAC',
            children: null,
            childDependentValue: 'Other conditions (please specify)',
            answerType: 'Text',
            dateFormat: null,
            answerDetails: null,
            answerPicklistChoices: [],
            answer: null,
            activationDate: null,
            activityDomain: null,
            expirationDate: null,
            loincCode: null,
            questionClassification: null,
            status: false,
            isPositive: false,
            yesIsPositive: false,
            payer: null,
            isAnswerValuePopulated: false,
            externalquestionId: null,
            ehrKey: null,
            hasTextDetail: true,
          },
        ],
        childDependentValue: null,
        answerType: 'Select Multiple',
        dateFormat: null,
        answerDetails: null,
        answerPicklistChoices: [
          'Heart disease or high blood pressure',
          'Depression',
          'Dementia',
          'Breathing problems caused by emphysema, COPD or asthma',
          'Schizophrenia',
          'Organ transplant',
          'Diabetes or other blood sugar problems',
          'Cancer',
          'Renal / kidney failure',
          'Anxiety',
          'Hearing and/or vision issues',
          'Heart failure or an enlarged heart',
          'Bipolar disorder',
          'Other conditions (please specify)',
        ],
        answer: null,
        activationDate: null,
        activityDomain: null,
        expirationDate: null,
        loincCode: null,
        questionClassification: null,
        status: false,
        isPositive: false,
        yesIsPositive: false,
        payer: null,
        isAnswerValuePopulated: false,
        externalquestionId: null,
        ehrKey: null,
        hasTextDetail: false,
      },
      {
        questionText: 'Do you have any trouble completing the following activities?',
        questionId: 'a0DO3000009Fk5YMAS',
        children: [
          {
            questionText: 'Bathing',
            questionId: 'a0DO3000009Fk5oMAC',
            children: null,
            childDependentValue: null,
            answerType: 'Select Single',
            dateFormat: null,
            answerDetails: null,
            answerPicklistChoices: [
              'I do not need help',
              'I need some help',
              'I am unable to do this activity without help',
            ],
            answer: null,
            activationDate: null,
            activityDomain: null,
            expirationDate: null,
            loincCode: null,
            questionClassification: null,
            status: false,
            isPositive: false,
            yesIsPositive: false,
            payer: null,
            isAnswerValuePopulated: false,
            externalquestionId: null,
            ehrKey: null,
            hasTextDetail: false,
          },
          {
            questionText: 'Getting Dressed',
            questionId: 'a0DO3000009Fk5pMAC',
            children: null,
            childDependentValue: null,
            answerType: 'Select Single',
            dateFormat: null,
            answerDetails: null,
            answerPicklistChoices: [
              'I do not need help',
              'I need some help',
              'I am unable to do this activity without help',
            ],
            answer: null,
            activationDate: null,
            activityDomain: null,
            expirationDate: null,
            loincCode: null,
            questionClassification: null,
            status: false,
            isPositive: false,
            yesIsPositive: false,
            payer: null,
            isAnswerValuePopulated: false,
            externalquestionId: null,
            ehrKey: null,
            hasTextDetail: false,
          },
          {
            questionText: 'Standing up and moving to another piece of \nfurniture',
            questionId: 'a0DO3000009Fk5qMAC',
            children: null,
            childDependentValue: null,
            answerType: 'Select Single',
            dateFormat: null,
            answerDetails: null,
            answerPicklistChoices: [
              'I do not need help',
              'I need some help',
              'I am unable to do this activity without help',
            ],
            answer: null,
            activationDate: null,
            activityDomain: null,
            expirationDate: null,
            loincCode: null,
            questionClassification: null,
            status: false,
            isPositive: false,
            yesIsPositive: false,
            payer: null,
            isAnswerValuePopulated: false,
            externalquestionId: null,
            ehrKey: null,
            hasTextDetail: false,
          },
          {
            questionText: 'Getting to and from the toilet',
            questionId: 'a0DO3000009Fk5rMAC',
            children: null,
            childDependentValue: null,
            answerType: 'Select Single',
            dateFormat: null,
            answerDetails: null,
            answerPicklistChoices: [
              'I do not need help',
              'I need some help',
              'I am unable to do this activity without help',
            ],
            answer: null,
            activationDate: null,
            activityDomain: null,
            expirationDate: null,
            loincCode: null,
            questionClassification: null,
            status: false,
            isPositive: false,
            yesIsPositive: false,
            payer: null,
            isAnswerValuePopulated: false,
            externalquestionId: null,
            ehrKey: null,
            hasTextDetail: false,
          },
          {
            questionText: 'Getting groceries',
            questionId: 'a0DO3000009Fk5sMAC',
            children: null,
            childDependentValue: null,
            answerType: 'Select Single',
            dateFormat: null,
            answerDetails: null,
            answerPicklistChoices: [
              'I do not need help',
              'I need some help',
              'I am unable to do this activity without help',
            ],
            answer: null,
            activationDate: null,
            activityDomain: null,
            expirationDate: null,
            loincCode: null,
            questionClassification: null,
            status: false,
            isPositive: false,
            yesIsPositive: false,
            payer: null,
            isAnswerValuePopulated: false,
            externalquestionId: null,
            ehrKey: null,
            hasTextDetail: false,
          },
          {
            questionText: 'Preparing meals',
            questionId: 'a0DO3000009Fk5tMAC',
            children: null,
            childDependentValue: null,
            answerType: 'Select Single',
            dateFormat: null,
            answerDetails: null,
            answerPicklistChoices: [
              'I do not need help',
              'I need some help',
              'I am unable to do this activity without help',
            ],
            answer: null,
            activationDate: null,
            activityDomain: null,
            expirationDate: null,
            loincCode: null,
            questionClassification: null,
            status: false,
            isPositive: false,
            yesIsPositive: false,
            payer: null,
            isAnswerValuePopulated: false,
            externalquestionId: null,
            ehrKey: null,
            hasTextDetail: false,
          },
          {
            questionText: 'Eating',
            questionId: 'a0DO3000009Fk5uMAC',
            children: null,
            childDependentValue: null,
            answerType: 'Select Single',
            dateFormat: null,
            answerDetails: null,
            answerPicklistChoices: [
              'I do not need help',
              'I need some help',
              'I am unable to do this activity without help',
            ],
            answer: null,
            activationDate: null,
            activityDomain: null,
            expirationDate: null,
            loincCode: null,
            questionClassification: null,
            status: false,
            isPositive: false,
            yesIsPositive: false,
            payer: null,
            isAnswerValuePopulated: false,
            externalquestionId: null,
            ehrKey: null,
            hasTextDetail: false,
          },
          {
            questionText: 'Bowel/Bladder control',
            questionId: 'a0DO3000009Fk5vMAC',
            children: null,
            childDependentValue: null,
            answerType: 'Select Single',
            dateFormat: null,
            answerDetails: null,
            answerPicklistChoices: [
              'I do not need help',
              'I need some help',
              'I am unable to do this activity without help',
            ],
            answer: null,
            activationDate: null,
            activityDomain: null,
            expirationDate: null,
            loincCode: null,
            questionClassification: null,
            status: false,
            isPositive: false,
            yesIsPositive: false,
            payer: null,
            isAnswerValuePopulated: false,
            externalquestionId: null,
            ehrKey: null,
            hasTextDetail: false,
          },
          {
            questionText: 'Taking your medications independently',
            questionId: 'a0DO3000009Fk5wMAC',
            children: null,
            childDependentValue: null,
            answerType: 'Select Single',
            dateFormat: null,
            answerDetails: null,
            answerPicklistChoices: [
              'I do not need help',
              'I need some help',
              'I am unable to do this activity without help',
            ],
            answer: null,
            activationDate: null,
            activityDomain: null,
            expirationDate: null,
            loincCode: null,
            questionClassification: null,
            status: false,
            isPositive: false,
            yesIsPositive: false,
            payer: null,
            isAnswerValuePopulated: false,
            externalquestionId: null,
            ehrKey: null,
            hasTextDetail: false,
          },
        ],
        childDependentValue: null,
        answerType: null,
        dateFormat: null,
        answerDetails: null,
        answerPicklistChoices: [],
        answer: null,
        activationDate: null,
        activityDomain: null,
        expirationDate: null,
        loincCode: null,
        questionClassification: null,
        status: false,
        isPositive: false,
        yesIsPositive: false,
        payer: null,
        isAnswerValuePopulated: false,
        externalquestionId: null,
        ehrKey: null,
        hasTextDetail: false,
      },
      {
        questionText: 'Please respond to the questions below: During the last 12 months',
        questionId: 'a0DO3000009Fk5UMAS',
        children: [
          {
            questionText: 'Was there a time you experienced pain which prevented you from completing things \nneeded for daily living?',
            questionId: 'a0DO3000009Fk5gMAC',
            children: null,
            childDependentValue: null,
            answerType: 'Select Single',
            dateFormat: null,
            answerDetails: null,
            answerPicklistChoices: [
              'Yes',
              'No',
              'I choose not to answer',
            ],
            answer: null,
            activationDate: null,
            activityDomain: null,
            expirationDate: null,
            loincCode: null,
            questionClassification: null,
            status: false,
            isPositive: false,
            yesIsPositive: false,
            payer: null,
            isAnswerValuePopulated: false,
            externalquestionId: null,
            ehrKey: null,
            hasTextDetail: false,
          },
          {
            questionText: 'Was there a time when you have been worried about running out of food?',
            questionId: 'a0DO3000009Fk5hMAC',
            children: null,
            childDependentValue: null,
            answerType: 'Select Single',
            dateFormat: null,
            answerDetails: null,
            answerPicklistChoices: [
              'Yes',
              'No',
              'I choose not to answer',
            ],
            answer: null,
            activationDate: null,
            activityDomain: null,
            expirationDate: null,
            loincCode: null,
            questionClassification: null,
            status: false,
            isPositive: false,
            yesIsPositive: false,
            payer: null,
            isAnswerValuePopulated: false,
            externalquestionId: null,
            ehrKey: null,
            hasTextDetail: false,
          },
          {
            questionText: 'Have you had any difficulty filling your medications or obtaining all the medications \nprescribed for you?',
            questionId: 'a0DO3000009Fk5iMAC',
            children: null,
            childDependentValue: null,
            answerType: 'Select Single',
            dateFormat: null,
            answerDetails: null,
            answerPicklistChoices: [
              'Yes',
              'No',
              'I choose not to answer',
            ],
            answer: null,
            activationDate: null,
            activityDomain: null,
            expirationDate: null,
            loincCode: null,
            questionClassification: null,
            status: false,
            isPositive: false,
            yesIsPositive: false,
            payer: null,
            isAnswerValuePopulated: false,
            externalquestionId: null,
            ehrKey: null,
            hasTextDetail: false,
          },
          {
            questionText: 'Have you taken your medications differently than they were prescribed?',
            questionId: 'a0DO3000009Fk5jMAC',
            children: null,
            childDependentValue: null,
            answerType: 'Select Single',
            dateFormat: null,
            answerDetails: null,
            answerPicklistChoices: [
              'Yes',
              'No',
              'I choose not to answer',
            ],
            answer: null,
            activationDate: null,
            activityDomain: null,
            expirationDate: null,
            loincCode: null,
            questionClassification: null,
            status: false,
            isPositive: false,
            yesIsPositive: false,
            payer: null,
            isAnswerValuePopulated: false,
            externalquestionId: null,
            ehrKey: null,
            hasTextDetail: false,
          },
          {
            questionText: 'Was there a time when you were not able to pay your mortgage, rent or utility bills?',
            questionId: 'a0DO3000009Fk5kMAC',
            children: null,
            childDependentValue: null,
            answerType: 'Select Single',
            dateFormat: null,
            answerDetails: null,
            answerPicklistChoices: [
              'Yes',
              'No',
              'I choose not to answer',
            ],
            answer: null,
            activationDate: null,
            activityDomain: null,
            expirationDate: null,
            loincCode: null,
            questionClassification: null,
            status: false,
            isPositive: false,
            yesIsPositive: false,
            payer: null,
            isAnswerValuePopulated: false,
            externalquestionId: null,
            ehrKey: null,
            hasTextDetail: false,
          },
          {
            questionText: 'Have you worried about losing your housing?',
            questionId: 'a0DO3000009Fk5lMAC',
            children: null,
            childDependentValue: null,
            answerType: 'Select Single',
            dateFormat: null,
            answerDetails: null,
            answerPicklistChoices: [
              'Yes',
              'No',
              'I choose not to answer',
            ],
            answer: null,
            activationDate: null,
            activityDomain: null,
            expirationDate: null,
            loincCode: null,
            questionClassification: null,
            status: false,
            isPositive: false,
            yesIsPositive: false,
            payer: null,
            isAnswerValuePopulated: false,
            externalquestionId: null,
            ehrKey: null,
            hasTextDetail: false,
          },
          {
            questionText: 'Have you become concerned regarding safety issues within your home?',
            questionId: 'a0DO3000009Fk5mMAC',
            children: null,
            childDependentValue: null,
            answerType: 'Select Single',
            dateFormat: null,
            answerDetails: null,
            answerPicklistChoices: [
              'Yes',
              'No',
              'I choose not to answer',
            ],
            answer: null,
            activationDate: null,
            activityDomain: null,
            expirationDate: null,
            loincCode: null,
            questionClassification: null,
            status: false,
            isPositive: false,
            yesIsPositive: false,
            payer: null,
            isAnswerValuePopulated: false,
            externalquestionId: null,
            ehrKey: null,
            hasTextDetail: false,
          },
        ],
        childDependentValue: null,
        answerType: null,
        dateFormat: null,
        answerDetails: null,
        answerPicklistChoices: [],
        answer: null,
        activationDate: null,
        activityDomain: null,
        expirationDate: null,
        loincCode: null,
        questionClassification: null,
        status: false,
        isPositive: false,
        yesIsPositive: false,
        payer: null,
        isAnswerValuePopulated: false,
        externalquestionId: null,
        ehrKey: null,
        hasTextDetail: false,
      },
      {
        questionText: 'What is your housing situation today?',
        questionId: 'a0DO3000009Fk5WMAS',
        children: null,
        childDependentValue: null,
        answerType: 'Select Single',
        dateFormat: null,
        answerDetails: null,
        answerPicklistChoices: [
          'I have housing',
          'I do not have housing (in a hotel, in a shelter, living outside on the street, on a beach, in a park)',
          'I choose not to answer this question',
        ],
        answer: null,
        activationDate: null,
        activityDomain: null,
        expirationDate: null,
        loincCode: null,
        questionClassification: null,
        status: false,
        isPositive: false,
        yesIsPositive: false,
        payer: null,
        isAnswerValuePopulated: false,
        externalquestionId: null,
        ehrKey: null,
        hasTextDetail: false,
      },
      {
        questionText: 'Has lack of reliable transportation kept you from medical appointments, work or from getting the things needed for daily living?',
        questionId: 'a0DO3000009Fk5XMAS',
        children: null,
        childDependentValue: null,
        answerType: 'Select Single',
        dateFormat: null,
        answerDetails: null,
        answerPicklistChoices: [
          'No',
          'It has kept me from medical appointments',
          'It has kept me from non-medical meetings, appointments, work, or from getting the things I need',
          'I choose not to answer this question',
        ],
        answer: null,
        activationDate: null,
        activityDomain: null,
        expirationDate: null,
        loincCode: null,
        questionClassification: null,
        status: false,
        isPositive: false,
        yesIsPositive: false,
        payer: null,
        isAnswerValuePopulated: false,
        externalquestionId: null,
        ehrKey: null,
        hasTextDetail: false,
      },
      {
        questionText: 'Would you like a Care Manager to outreach to you to assist with your health concerns, \nmedication, community resources, or other questions/concerns?',
        questionId: 'a0DO3000009Fk5TMAS',
        children: null,
        childDependentValue: null,
        answerType: 'Select Single',
        dateFormat: null,
        answerDetails: null,
        answerPicklistChoices: [
          'Yes',
          'No',
        ],
        answer: null,
        activationDate: null,
        activityDomain: null,
        expirationDate: null,
        loincCode: null,
        questionClassification: null,
        status: false,
        isPositive: false,
        yesIsPositive: false,
        payer: null,
        isAnswerValuePopulated: false,
        externalquestionId: null,
        ehrKey: null,
        hasTextDetail: false,
      },
    ],
    name: 'Carefirst Health Risk Assessment 2025 UPDATED',
    isStarted: false,
    isCompleted: false,
    completionDate: null,
    agentName: 'Tamoghna Dey',
    memberId: null,
    memberLifetimeID: null,
    mbi: null,
    hContract: 'H57348',
  },
  currentQuestionIndex: 0,
  status: 'notStarted',
  answers: {
    a0DO3000009Fk5OMAS: 'English',
    a0DO3000009Fk5NMAS: 'Good',
    a0DO3000009Fk5QMAS: 'Yes',
    a0DO3000009Fk5PMAS: 'Yes',
    a0DO3000009Fk5RMAS: 'Yes',
    a0DO3000009Fk5SMAS: [
      'Walker',
      'Wheelchair',
    ],
    a0DO3000009Fk5ZMAS: 'No',
    a0DO3000009Fk5aMAC: 'Yes',
    a0DO3000009Fk5yMAC: 'asdads',
    a0DO3000009Fk5bMAC: 'Yes',
    a0DO3000009Fk5zMAC: '2-3 times',
    a0DO3000009Fk5cMAC: 'Previous',
    a0DO3000009Fk5dMAC: [
      'Used recreational or street drugs',
      'Used prescription drugs for non-medical reasons',
    ],
    a0DO3000009Fk5eMAC: 'Yes',
    a0DO3000009Fk5VMAS: [
      'Depression',
      'Dementia',
      'Other conditions (please specify)',
    ],
    a0DO3000009Fk5oMAC: 'I do not need help',
    a0DO3000009Fk5pMAC: 'I need some help',
    a0DO3000009Fk5qMAC: 'I need some help',
    a0DO3000009Fk5rMAC: 'I do not need help',
    a0DO3000009Fk5sMAC: 'I need some help',
    a0DO3000009Fk5tMAC: 'I need some help',
    a0DO3000009Fk5uMAC: 'I need some help',
    a0DO3000009Fk5vMAC: 'I need some help',
    a0DO3000009Fk5wMAC: 'I need some help',
    a0DO3000009Fk5gMAC: 'Yes',
    a0DO3000009Fk5hMAC: 'No',
    a0DO3000009Fk5iMAC: 'No',
    a0DO3000009Fk5jMAC: 'No',
    a0DO3000009Fk5kMAC: 'No',
    a0DO3000009Fk5lMAC: 'I choose not to answer',
    a0DO3000009Fk5mMAC: 'I choose not to answer',
    a0DO3000009Fk5WMAS: 'I do not have housing (in a hotel, in a shelter, living outside on the street, on a beach, in a park)',
    a0DO3000009Fk5XMAS: 'It has kept me from medical appointments',
    a0DO3000009Fk5TMAS: 'Yes',
  },
}
