import { Visit, EquipmentItem } from './types'

export const equipmentDataToday: EquipmentItem[] = [
  { name: 'HbA1c Kit', visits: 3 },
  { name: 'Lipid Panel Kit', visits: 2 },
  { name: 'Microalbumin Kit', visits: 1 },
  { name: 'FIT/FOBT Kit', visits: 1 },
  { name: 'Retinal Camera', visits: 1 },
  { name: 'Bone Density Kit', visits: 1 },
  { name: 'Portable ECG/EKG', visits: 1 },
  { name: 'Vaccine Kit', visits: 1 },
  { name: 'STI Kit', visits: 1 },
]

export const equipmentDataTomorrow: EquipmentItem[] = [
  { name: 'HbA1c Kit', visits: 2 },
  { name: 'Lipid Panel Kit', visits: 1 },
  { name: 'Retinal Camera', visits: 1 },
  { name: 'Portable ECG/EKG', visits: 1 },
  { name: 'Vaccine Kit', visits: 1 },
]

export const equipmentDataWeek: EquipmentItem[] = [
  { name: 'HbA1c Kit', visits: 11 },
  { name: 'Lipid Panel Kit', visits: 12 },
  { name: 'Microalbumin Kit', visits: 8 },
  { name: 'FIT/FOBT Kit', visits: 9 },
  { name: 'Pap/HPV Kit', visits: 5 },
  { name: 'Retinal Camera', visits: 13 },
  { name: 'Spirometry Kit', visits: 10 },
  { name: 'Bone Density Kit', visits: 12 },
  { name: 'Portable ECG/EKG', visits: 9 },
  { name: 'Vaccine Kit', visits: 9 },
  { name: 'Portable Ultrasound', visits: 8 },
  { name: 'STI Kit', visits: 11 },
  { name: 'Hep C Kit', visits: 9 },
  { name: 'HIV Kit', visits: 12 },
]

export const mockVisitsToday: Visit[] = [
  {
    id: '1',
    patientName: 'Jane Smith',
    time: '10:30AM',
    address: '1234 Main Street, Dayton, OH',
    phone: '(570) 555-0001',
    insurance: 'UHC',
    status: 'not-started',
    visitType: 'in-home',
    procedures: [
      { name: 'A1C' },
      { name: 'Blood Pressure', completed: true},
      { name: 'Urine Sample' },
    ],
    healthRiskAssessment: 'not-started',
    consentForms: [
      { name: 'HIPAA Authorization' },
      { name: 'Notice of Privacy Practices' },
      { name: 'Treatment Consent' },
    ],
  },
  {
    id: '2',
    patientName: 'John Doe',
    time: '11:00AM',
    address: '5678 Oak Avenue, Dayton, OH',
    phone: '(570) 555-0002',
    insurance: 'Aetna',
    status: 'not-started',
    visitType: 'telehealth',
    procedures: [
      { name: 'A1C', completed: true },
      { name: 'Blood Pressure', completed: true },
      { name: 'Urine Sample' },
    ],
    healthRiskAssessment: 'in-progress',
    consentForms: [
      { name: 'HIPAA Authorization', completed: true },
      { name: 'Notice of Privacy Practices' },
      { name: 'Treatment Consent' },
    ],
  },
  {
    id: '3',
    patientName: 'John Doe',
    time: '11:00AM',
    address: '5678 Oak Avenue, Dayton, OH',
    phone: '(570) 555-0003',
    insurance: 'Aetna',
    status: 'not-started',
    visitType: 'telehealth',
    procedures: [
      { name: 'A1C', completed: true },
      { name: 'Blood Pressure', completed: true },
      { name: 'Urine Sample' },
    ],
    healthRiskAssessment: 'not-started',
    consentForms: [
      { name: 'HIPAA Authorization' },
      { name: 'Notice of Privacy Practices' },
      { name: 'Treatment Consent' },
    ],
  },
  {
    id: '4',
    patientName: 'John Doe',
    time: '11:00AM',
    address: '5678 Oak Avenue, Dayton, OH',
    phone: '(570) 555-0004',
    insurance: 'Aetna',
    status: 'not-started',
    visitType: 'telehealth',
    procedures: [
      { name: 'A1C', completed: true },
      { name: 'Blood Pressure', completed: true },
      { name: 'Urine Sample' },
    ],
    healthRiskAssessment: 'in-progress',
    consentForms: [
      { name: 'HIPAA Authorization' },
      { name: 'Notice of Privacy Practices', completed: true },
      { name: 'Treatment Consent' },
    ],
  },
]

export const mockVisitsTomorrow: Visit[] = [
  {
    id: 'tom-1',
    patientName: 'Sarah Williams',
    time: '9:00AM',
    address: '789 Maple Street, Dayton, OH',
    phone: '(570) 555-1001',
    insurance: 'Medicare',
    status: 'not-started',
    visitType: 'in-home',
    procedures: [{ name: 'HbA1c Test' }, { name: 'Blood Pressure' }, { name: 'Lipid Panel' }],
    healthRiskAssessment: 'not-started',
    consentForms: [
      { name: 'HIPAA Authorization' },
      { name: 'Notice of Privacy Practices' },
      { name: 'Treatment Consent' },
    ],
  },
  {
    id: 'tom-2',
    patientName: 'Michael Chen',
    time: '10:30AM',
    address: '456 Pine Avenue, Dayton, OH',
    phone: '(570) 555-1002',
    insurance: 'BCBS',
    status: 'not-started',
    visitType: 'telehealth',
    procedures: [{ name: 'Retinal Screening' }, { name: 'Blood Pressure' }],
    healthRiskAssessment: 'not-started',
    consentForms: [
      { name: 'HIPAA Authorization' },
      { name: 'Notice of Privacy Practices' },
      { name: 'Treatment Consent' },
    ],
  },
  {
    id: 'tom-3',
    patientName: 'Emily Rodriguez',
    time: '1:00PM',
    address: '321 Cedar Lane, Dayton, OH',
    phone: '(570) 555-1003',
    insurance: 'UHC',
    status: 'not-started',
    visitType: 'in-home',
    procedures: [{ name: 'EKG' }, { name: 'Vaccine' }, { name: 'Blood Pressure' }],
    healthRiskAssessment: 'not-started',
    consentForms: [
      { name: 'HIPAA Authorization' },
      { name: 'Notice of Privacy Practices' },
      { name: 'Treatment Consent' },
    ],
  },
]

export const mockVisitsWeek: Visit[] = [
  {
    id: '1',
    patientName: 'Emily Davis',
    time: '9:30AM',
    address: '5678 Oak Avenue, Dayton, OH',
    phone: '(570) 555-0101',
    insurance: 'Medicare',
    status: 'not-started',
    visitType: 'telehealth',
    date: 'Thursday, August 6, 2025',
    procedures: [
      { name: 'Ultrasound' },
      { name: 'FIT/FOBT Test' },
      { name: 'Microalbumin Test' },
      { name: 'Spirometry Test' },
    ],
    healthRiskAssessment: 'not-started',
    consentForms: [
      { name: 'HIPAA Authorization' },
      { name: 'Notice of Privacy Practices' },
      { name: 'Treatment Consent' },
    ],
  },
  {
    id: '2',
    patientName: 'Brandon Young',
    time: '1:00PM',
    address: '147 Willow Court, Englewo...',
    phone: '(570) 555-0102',
    insurance: 'BCBS',
    status: 'not-started',
    visitType: 'in-home',
    date: 'Thursday, August 6, 2025',
    procedures: [
      { name: 'EKG' },
      { name: 'Hepatitis C Test' },
      { name: 'HIV Test' },
      { name: 'FIT/FOBT Test' },
    ],
    healthRiskAssessment: 'not-started',
    consentForms: [
      { name: 'HIPAA Authorization' },
      { name: 'Notice of Privacy Practices' },
      { name: 'Treatment Consent' },
    ],
  },
  {
    id: '3',
    patientName: 'Sarah Johnson',
    time: '10:00AM',
    address: '789 Pine Street, Dayton, OH',
    phone: '(570) 555-0103',
    insurance: 'Aetna',
    status: 'not-started',
    visitType: 'in-home',
    date: 'Thursday, August 7, 2025',
    procedures: [
      { name: 'HbA1c Test' },
      { name: 'Blood Pressure' },
      { name: 'Retinal Screening' },
    ],
    healthRiskAssessment: 'not-started',
    consentForms: [
      { name: 'HIPAA Authorization' },
      { name: 'Notice of Privacy Practices' },
      { name: 'Treatment Consent' },
    ],
  },
  {
    id: '4',
    patientName: 'Michael Brown',
    time: '2:30PM',
    address: '321 Oak Avenue, Dayton, OH',
    phone: '(570) 555-0104',
    insurance: 'UHC',
    status: 'not-started',
    visitType: 'in-home',
    date: 'Thursday, August 7, 2025',
    procedures: [
      { name: 'Lipid Panel' },
      { name: 'Bone Density' },
      { name: 'Vaccine' },
    ],
    healthRiskAssessment: 'not-started',
    consentForms: [
      { name: 'HIPAA Authorization' },
      { name: 'Notice of Privacy Practices' },
      { name: 'Treatment Consent' },
    ],
  },
  {
    id: '5',
    patientName: 'Lisa Wilson',
    time: '11:00AM',
    address: '5678 Oak Avenue, Dayton, OH',
    phone: '(570) 555-0105',
    insurance: 'Medicare',
    status: 'not-started',
    visitType: 'telehealth',
    date: 'Thursday, August 8, 2025',
    procedures: [
      { name: 'Pap/HPV Test' },
      { name: 'STI Testing' },
      { name: 'HIV Test' },
    ],
    healthRiskAssessment: 'not-started',
    consentForms: [
      { name: 'HIPAA Authorization' },
      { name: 'Notice of Privacy Practices' },
      { name: 'Treatment Consent' },
    ],
  },
  {
    id: '6',
    patientName: 'David Miller',
    time: '3:00PM',
    address: '456 Elm Street, Dayton, OH',
    phone: '(570) 555-0106',
    insurance: 'BCBS',
    status: 'not-started',
    visitType: 'in-home',
    date: 'Thursday, August 8, 2025',
    procedures: [
      { name: 'Portable ECG' },
      { name: 'Hepatitis C Test' },
      { name: 'FIT/FOBT Test' },
    ],
    healthRiskAssessment: 'not-started',
    consentForms: [
      { name: 'HIPAA Authorization' },
      { name: 'Notice of Privacy Practices' },
      { name: 'Treatment Consent' },
    ],
  },
  {
    id: '7',
    patientName: 'Jennifer Garcia',
    time: '9:00AM',
    address: '654 Maple Drive, Dayton, OH',
    phone: '(570) 555-0107',
    insurance: 'Aetna',
    status: 'not-started',
    visitType: 'in-home',
    date: 'Friday, August 9, 2025',
    procedures: [
      { name: 'Microalbumin Test' },
      { name: 'Spirometry Test' },
      { name: 'Vaccine' },
    ],
    healthRiskAssessment: 'not-started',
    consentForms: [
      { name: 'HIPAA Authorization' },
      { name: 'Notice of Privacy Practices' },
      { name: 'Treatment Consent' },
    ],
  },
  {
    id: '8',
    patientName: 'Robert Taylor',
    time: '1:30PM',
    address: '987 Cedar Lane, Dayton, OH',
    phone: '(570) 555-0108',
    insurance: 'UHC',
    status: 'not-started',
    visitType: 'in-home',
    date: 'Friday, August 9, 2025',
    procedures: [
      { name: 'Retinal Camera' },
      { name: 'Bone Density' },
      { name: 'Portable Ultrasound' },
    ],
    healthRiskAssessment: 'not-started',
    consentForms: [
      { name: 'HIPAA Authorization' },
      { name: 'Notice of Privacy Practices' },
      { name: 'Treatment Consent' },
    ],
  },
  {
    id: '9',
    patientName: 'Maria Rodriguez',
    time: '10:30AM',
    address: '5678 Oak Avenue, Dayton, OH',
    phone: '(570) 555-0109',
    insurance: 'Medicare',
    status: 'not-started',
    visitType: 'telehealth',
    date: 'Monday, August 12, 2025',
    procedures: [
      { name: 'HbA1c Test' },
      { name: 'Lipid Panel' },
      { name: 'Blood Pressure' },
    ],
    healthRiskAssessment: 'not-started',
    consentForms: [
      { name: 'HIPAA Authorization' },
      { name: 'Notice of Privacy Practices' },
      { name: 'Treatment Consent' },
    ],
  },
  {
    id: '10',
    patientName: 'James Anderson',
    time: '2:00PM',
    address: '123 Birch Street, Dayton, OH',
    phone: '(570) 555-0110',
    insurance: 'BCBS',
    status: 'not-started',
    visitType: 'in-home',
    date: 'Monday, August 12, 2025',
    procedures: [
      { name: 'EKG' },
      { name: 'HIV Test' },
      { name: 'Hepatitis C Test' },
    ],
    healthRiskAssessment: 'not-started',
    consentForms: [
      { name: 'HIPAA Authorization' },
      { name: 'Notice of Privacy Practices' },
      { name: 'Treatment Consent' },
    ],
  },
  {
    id: '11',
    patientName: 'Patricia White',
    time: '4:30PM',
    address: '789 Cedar Avenue, Dayton, OH',
    phone: '(570) 555-0111',
    insurance: 'UHC',
    status: 'not-started',
    visitType: 'in-home',
    date: 'Monday, August 12, 2025',
    procedures: [
      { name: 'Blood Pressure' },
      { name: 'Vaccine' },
    ],
    healthRiskAssessment: 'not-started',
    consentForms: [
      { name: 'HIPAA Authorization' },
      { name: 'Notice of Privacy Practices' },
      { name: 'Treatment Consent' },
    ],
  },
  {
    id: '12',
    patientName: 'Thomas Clark',
    time: '6:00PM',
    address: '456 Pine Street, Dayton, OH',
    phone: '(570) 555-0112',
    insurance: 'Medicare',
    status: 'not-started',
    visitType: 'in-home',
    date: 'Monday, August 12, 2025',
    procedures: [
      { name: 'Lipid Panel' },
      { name: 'HbA1c Test' },
    ],
    healthRiskAssessment: 'not-started',
    consentForms: [
      { name: 'HIPAA Authorization' },
      { name: 'Notice of Privacy Practices' },
      { name: 'Treatment Consent' },
    ],
  },
  {
    id: '13',
    patientName: 'Piter Clark',
    time: '7:00PM',
    address: '456 Pine Street, Dayton, OH',
    phone: '(570) 555-0113',
    insurance: 'Medicare',
    status: 'not-started',
    visitType: 'in-home',
    date: 'Monday, August 12, 2025',
    procedures: [
      { name: 'Lipid Panel' },
      { name: 'HbA1c Test' },
    ],
    healthRiskAssessment: 'not-started',
    consentForms: [
      { name: 'HIPAA Authorization' },
      { name: 'Notice of Privacy Practices' },
      { name: 'Treatment Consent' },
    ],
  },
]
