name: Provision Infrastructure Resources

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        default: "sandbox"
        type: choice
        options:
          - sandbox
          - development
          - qa
          - production

jobs:
  plan:
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    env:
      BUCKET_NAME: ${{ vars.S3_BUCKET_NAME }}
      AWS_ACCESS_KEY_ID: ${{ secrets[format('AWS_{0}_ACCESS_KEY_ID', github.event.inputs.environment == 'sandbox' && 'SBX' || github.event.inputs.environment == 'development' && 'DEV' || github.event.inputs.environment == 'qa' && 'QA' || github.event.inputs.environment == 'production' && 'PROD')] }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets[format('AWS_{0}_SECRET_ACCESS_KEY', github.event.inputs.environment == 'sandbox' && 'SBX' || github.event.inputs.environment == 'development' && 'DEV' || github.event.inputs.environment == 'qa' && 'QA' || github.event.inputs.environment == 'production' && 'PROD')] }}

    permissions:
      id-token: write
      contents: read

    outputs:
      bucket_name: ${{ env.BUCKET_NAME }}
      aws_access_key_id: ${{ env.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ env.AWS_SECRET_ACCESS_KEY }}

    steps:
    # Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_PAT }}
        submodules: 'recursive'

    # Setup Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.2.8

    # Terraform Init
    - name: Terraform Init
      working-directory: .deployments/root
      run: terraform init -backend-config="../backend/${{ github.event.inputs.environment }}.tfvars"

    # Terraform Validate
    - name: Terraform Validate
      run: terraform validate

    # Terraform Plan
    - name: Terraform Plan
      id: plan
      working-directory: .deployments/root
      run: terraform plan -var-file="../config/${{ github.event.inputs.environment }}.tfvars" -out=tfplan
      
    - name: Upload Plan
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: tfplan
        path: .deployments/root/tfplan
        
  request-approval:
    needs: plan
    runs-on: ubuntu-latest
    environment:
      name: "${{ github.event.inputs.environment }}"
    steps:
      - name: Wait for Approval
        run: echo "Waiting for approval..."
        timeout-minutes: 5

  deploy:
    needs: request-approval
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.approved != 'false' }}
    env:
      BUCKET_NAME: ${{ vars.S3_BUCKET_NAME }}
      AWS_ACCESS_KEY_ID: ${{ secrets[format('AWS_{0}_ACCESS_KEY_ID', github.event.inputs.environment == 'sandbox' && 'SBX' || github.event.inputs.environment == 'development' && 'DEV' || github.event.inputs.environment == 'qa' && 'QA' || github.event.inputs.environment == 'production' && 'PROD')] }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets[format('AWS_{0}_SECRET_ACCESS_KEY', github.event.inputs.environment == 'sandbox' && 'SBX' || github.event.inputs.environment == 'development' && 'DEV' || github.event.inputs.environment == 'qa' && 'QA' || github.event.inputs.environment == 'production' && 'PROD')] }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.8

      - name: Debug Environment Variables
        run: |
          echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
          echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
          echo "BUCKET_NAME: $BUCKET_NAME"
      - name: Download Plan
        uses: actions/download-artifact@v3
        with:
          name: tfplan
          path: .deployments/root

      - name: Terraform Init
        working-directory: .deployments/root
        run: terraform init -backend-config="../backend/${{ github.event.inputs.environment }}.tfvars"

      - name: Terraform Apply
        working-directory: .deployments/root
        run: terraform apply -auto-approve tfplan