name: Deploy Provider Portal

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        default: "Sandbox"
        type: choice
        options:
          - Sandbox
          - Development
          - QA
          - Production

jobs:
  deploy:
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    env:
      BUCKET_NAME: ${{ vars.S3_BUCKET_NAME }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      VITE_APP_MSAL_REDIRECT_URI: ${{ vars.MSAL_REDIRECT_URI }}
      VITE_HRA_SERVICE_API_URL: ${{ vars.HRA_SERVICE_API_URL }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_PAT }}
        submodules: 'recursive'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.17.0'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install Dependencies
      run: pnpm install

    - name: Build Application
      run: pnpm build
      env:
        VITE_APP_MSAL_REDIRECT_URI: ${{ vars.MSAL_REDIRECT_URI }}
        VITE_DEV_TEST: ${{ github.event.inputs.environment == 'Sandbox' }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to S3
      run: |
        aws s3 sync ./dist s3://${{ env.BUCKET_NAME }} --delete

    - name: ZAP Scan
      uses: zaproxy/action-full-scan@v0.8.0
      with:
        target: ${{ vars.MSAL_REDIRECT_URI }}
        token: ${{ secrets.GITHUB_TOKEN }}
